### ISSUE TITLE
Status request

### ISSUE THREAD

**Issue by DeflateAwning** [secworks/blake2s#1]
What is the status of each part of this project? Which blocks need the most work? Can you give some guidance on how I can begin to help with the development of this project? Thanks!

**Comment by secworks** [comment]
Status right now is unfortunately quite unknown. There are two testbenches - one for the GF function and one for the message word select function. Running the gf testcase seems to give a result back. It might be a correct check. the m_select also produces some real results. They may also be correct. One step is to check that they can be trusted. If so, move up the chain towards the actual rounds. That would mean starting to work on the blake2s_core.v and its associated testbench tb_blake2s_core.v.

One could also consider creating a separate submodule for the round function itself. That might be easier to debug. So a blake2s_round.v and tb_blake2s_round.v.

In order to get some test vectors to drive the debugging I would modify the reference model (under src/model/reference) to spit out valid inputs and outputs for the round function during testing. That should give you plenty of values to use as test cases.

Oh, and I suggest starting by forking the repo so that you can work on your version and then create merge requests. I'm slightly picky on how the code is implemented and want the style to be very consistent over all cores. ;-)

I will probably not have time to do any work myself before the weekend.

**Comment by secworks** [comment]
Looking at the code, the Makefile, it seems to be in a pretty sordid state.

**Comment by secworks** [comment]
I've added rtl and testbench files for round and core. I've also updated the Makefile to include build and sim targets for round and core. I see many bad things in the code. But all targets builds.

**Comment by ThePiGuy** [comment]
I'm having trouble figuring out what next step I should take. I'm wondering if there's any chance you could help me get started on the blake2s_round.v system, with a little bit of direction and the associated section of the model to implement? No hurry or anything though!

**Comment by secworks** [comment]
What I've started to do is to work on testcases for the blake2s reference model. I have now three testcases. With them it should be possible to instrument the reference model to see the inner workings. And use that to drive the implementation. I'm reasonably sure that the G-function is ok. And probably the m-select. This means that what is left is basically connecting these modules together to form a working round function. So right now I don't think it is worth having that as a separate module.

One thing that will be needed and is tricky is to get the final block padding done. We need to add a counter for that, and be able to do some arithmetic with it.

**Comment by secworks** [comment]
I've actually started to work on completing the implementation. I have instrumented the reference model enough to be able to implement the core. The round module will not be needed.

**Comment by ThePiGuy** [comment]
Exciting stuff! Great work! Looking forward to seeing what you come up with!

**Comment by secworks** [comment]
Unfortunately I got overwhelmed again. Hopefully I will find some time next week.

**Comment by secworks** [comment]
There is at least a complete testcase in tb_blake2s_core.v that should be usable to test all part of mesage processing. The reference model have the same test and can be used to check intermediate results etc.

**Comment by secworks** [comment]
I have now actually completed the core! It needs to be tested in real HW (FPGAs), but simulates ok. I think the core looks ok.
